
#line 3 "lex.yy.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer yyFlexLexer

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream> 
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::istream* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 153
#define YY_END_OF_BUFFER 154
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[496] =
    {   0,
        0,    0,  154,  152,  148,  130,  130,   88,  152,  147,
       99,   94,  146,   81,   82,   95,   90,  125,   91,   87,
       98,  132,  131,  113,  127,  102,  114,  104,  112,  135,
      135,   83,   84,  108,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,  128,  109,  129,   89,  148,  107,
        0,  143,  142,    0,  147,  147,  117,  110,  120,  146,
      145,  144,  146,  115,   92,  118,   93,  119,   85,   96,
        0,  138,  151,  149,  116,  136,  132,  137,  140,  137,
      132,  132,  134,  131,  131,  131,   86,  100,  103,  106,

      105,  101,  135,    0,  146,  121,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,   14,  135,  135,  135,
      135,  135,  135,  135,  135,  135,   27,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  122,  111,  147,   97,
      126,  141,  138,  151,  151,  151,  149,  136,  139,  136,
      140,  137,  132,  132,  132,  133,  131,  131,  131,  123,
      124,  135,  135,  135,  135,  135,  135,  135,   66,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,

      135,  135,  135,  135,   24,  135,  135,  135,   29,  135,
      135,   70,  135,  135,   33,  135,  135,  135,  135,  135,
      135,  135,  135,  135,   71,  135,  135,  135,  135,   65,
      135,  135,  135,  135,  135,  135,   53,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  147,  147,
      141,  138,  150,  139,  136,  139,  136,  132,  133,  133,
      131,    1,    3,  135,    4,  135,  135,    7,  135,  135,
      135,   67,  135,  135,  135,  135,  135,   17,   79,   18,
      135,  135,  135,  135,  135,  135,   26,  135,   75,   30,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,

      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      135,   50,  135,   52,  135,  135,  135,  135,  135,  135,
      135,   61,  135,  135,  135,  139,  136,  133,  133,  133,
        2,    5,    6,    8,    9,  135,  135,  135,   72,  135,
      135,  135,  135,  135,   22,   23,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,   74,  135,  135,  135,
       42,  135,  135,  135,   76,  135,  135,  135,  135,  135,
       51,  135,  135,  135,   57,  135,  135,   59,  135,  135,
      135,  135,   64,  133,  135,  135,  135,   13,   15,  135,
      135,   20,   21,   25,   28,  135,  135,  135,   35,  135,

      135,  135,   38,  135,  135,   41,   43,   69,   44,   45,
       80,   47,   48,  135,  135,   55,  135,  135,  135,   68,
      135,  135,  135,  135,  135,   12,  135,  135,   31,  135,
      135,  135,   36,  135,  135,  135,  135,  135,   54,  135,
      135,  135,   60,  135,   63,  135,   11,  135,   19,  135,
       34,  135,  135,   39,  135,  135,   49,   56,  135,   58,
       62,  135,  135,   32,  135,   37,  135,  135,  135,   10,
      135,  135,  135,  135,  135,  135,  135,  135,   46,  135,
      135,   16,  135,  135,  135,  135,  135,  135,   77,   78,
       73,  135,  135,   40,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   28,   28,   28,   29,   30,
       31,   31,   31,   31,   31,   32,   31,   31,   31,   31,
       31,   31,   31,   31,   33,   31,   31,   34,   31,   31,
       35,   36,   37,   38,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   31,   49,   50,   51,   52,
       53,   54,   55,   56,   57,   58,   59,   60,   61,   62,
       63,   64,   65,   66,   67,   68,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[69] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        3,    1,    1,    1,    1,    1,    1,    3,    3,    3,
        4,    4,    4,    4,    1,    1,    1,    1,    4,    3,
        3,    3,    3,    3,    3,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[505] =
    {   0,
        0,    0,  667,  668,  664,  668,  668,  640,   66,  628,
      638,   61,   68,  668,  668,  637,   59,  668,   63,   74,
       67,   88,  134,  639,  668,   50,  635,   51,  668,    0,
       90,  668,  668,  634,  599,   45,   63,   71,   73,   86,
      604,   38,   66,   72,   97,  602,   87,  596,  610,  101,
      113,  104,  124,  123,  668,   74,  668,  668,  651,  668,
      168,  668,  668,    0,  616,  648,  668,  668,  668,  170,
      668,  668,    0,  668,  668,  668,  668,  668,  637,  668,
      632,  166,  170,    0,  668,  170,   96,  202,  219,  668,
      192,  162,    0,    0,  194,  186,  668,  623,  668,  668,

      668,  622,    0,  242,  172,  668,  588,  592,  600,   24,
      599,  602,  589,  600,  178,  204,  580,  586,  580,   85,
      143,  586,  582,  578,  585,  574,    0,  155,  574,  578,
      575,  570,  576,  565,  581,  567,  202,  582,  578,  210,
      563,  567,  197,  217,  571,  567,  161,  144,  563,  214,
      568,  573,  558,  215,  566,  564,  668,  668,  575,  668,
      668,  256,  668,  251,  261,  267,    0,  262,  279,  668,
      267,  283,  251,  668,  258,  264,  268,  668,  279,  668,
      668,  557,  559,  568,  563,  564,  563,  548,    0,  546,
      171,  544,  561,  556,  540,  557,  557,  552,  545,  543,

      266,  549,  535,  551,    0,  546,  536,  540,    0,  529,
      540,    0,  545,  540,    0,  527,  540,  264,  523,  530,
      520,  530,  525,  517,    0,  519,  522,  529,  247,    0,
      133,  514,  517,  513,  516,  524,    0,  523,  513,  509,
      516,  511,  504,  503,  517,  519,  518,  507,  520,  552,
      301,  311,  668,  326,  668,  315,  318,  668,  319,  294,
      668,    0,    0,  505,    0,  506,  502,    0,  494,  492,
      501,    0,  489,  489,  502,  495,  493,    0,    0,    0,
      495,  486,  485,  496,  481,  486,    0,  485,    0,    0,
      495,  478,  494,  493,  476,  491,  486,  481,  484,  470,

      468,  469,  466,  479,  314,  473,  473,  468,  477,  476,
      467,    0,  455,    0,  306,  463,  471,  467,  466,  458,
      451,    0,  451,  452,  463,  345,  351,  326,  668,  323,
        0,    0,    0,    0,  467,  453,  454,  459,    0,  458,
      453,  458,  441,  446,    0,    0,  454,  452,  445,  440,
      435,  442,  443,  432,  447,  446,    0,  429,  442,  433,
        0,  441,  425,  437,    0,  439,  434,  421,  431,  437,
        0,  432,  432,  434,    0,  429,  420,    0,  415,  430,
      421,  429,    0,  668,  425,  407,  407,    0,    0,  422,
      415,    0,    0,    0,    0,  418,  421,  407,    0,  401,

      414,  399,    0,  412,  399,    0,    0,    0,    0,  415,
        0,    0,    0,  395,  407,    0,  400,  394,  405,    0,
      398,  397,  388,  405,  400,    0,  404,  384,    0,  399,
      384,  376,    0,  394,  381,  382,  393,  390,    0,  389,
      388,  382,    0,  377,    0,  350,    0,  358,    0,  355,
        0,  359,  354,    0,  339,  354,    0,    0,  350,    0,
        0,  334,  351,    0,  335,    0,  345,  331,  348,    0,
      329,  325,  324,  321,  323,  319,  332,  336,    0,  322,
      316,    0,  298,  283,  264,  251,  222,  201,    0,    0,
        0,   95,   71,    0,  668,  401,  405,  409,  411,  415,

      419,   94,  423,  427
    } ;

static yyconst flex_int16_t yy_def[505] =
    {   0,
      495,    1,  495,  495,  495,  495,  495,  495,  496,  497,
      495,  495,  498,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  499,
      499,  495,  495,  495,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  495,  495,  495,  495,  495,  495,
      496,  495,  495,  496,  497,  497,  495,  495,  495,  498,
      495,  495,  498,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  500,  501,  495,  495,   22,  495,  495,  495,
      495,  495,  502,   23,  495,  495,  495,  495,  495,  495,

      495,  495,  499,  496,  498,  495,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  495,  495,  503,  495,
      495,  495,  495,  500,  504,  500,  501,  495,  495,  495,
      495,  495,  495,  495,  495,  502,  495,  495,  495,  495,
      495,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,

      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  503,  503,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,

      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  495,  495,  495,  495,  495,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  495,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,

      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,    0,  495,  495,  495,  495,  495,

      495,  495,  495,  495
    } ;

static yyconst flex_int16_t yy_nxt[737] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       23,   24,   25,   26,   27,   28,   29,   30,   30,   30,
       30,   31,   30,   30,   32,    4,   33,   34,   30,   35,
       36,   37,   38,   39,   40,   41,   30,   42,   30,   43,
       44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
       54,   30,   30,   30,   55,   56,   57,   58,   62,   68,
       71,   63,   75,   98,   99,  101,  102,   72,   77,   83,
      185,  186,  127,   76,   84,   69,   80,   78,   79,  128,
       81,   85,   82,   82,   82,  104,  176,  108,  157,  105,

      109,   64,  110,   73,   86,  111,   87,   87,   88,  112,
      113,  131,  114,  129,  116,  115,   89,   90,  130,   91,
       92,   93,  119,  117,  120,  122,  136,  199,  494,  495,
      132,   89,   90,  118,  121,  123,  133,   91,  124,  158,
      134,  125,  137,  200,  141,  138,   92,  142,  143,   93,
       86,  493,   94,   94,   94,  150,  146,  495,  144,  147,
      151,  145,   89,   90,  155,   95,   96,  152,  148,  156,
       62,  153,   71,   63,   71,  149,  154,   89,   90,   72,
      308,   72,  165,   95,   82,   82,   82,  166,  168,  168,
      168,  309,   96,  175,  162,  163,  201,  163,  169,  170,

      202,  170,  236,   64,  208,   73,  237,   73,  234,  162,
      163,  175,  209,  169,  170,  163,  235,  179,   86,  170,
       88,   88,   88,  173,  174,  177,  178,  270,  271,  191,
       89,   90,  171,   90,  171,  179,  192,  172,  172,  172,
      492,  173,  227,  177,   62,   89,   90,   63,  193,  218,
      174,   90,  178,  194,  219,  222,  229,  223,  195,  230,
      228,  239,  245,  165,  246,  491,  240,  224,  166,  251,
      241,  251,  231,  165,  252,  252,  252,   64,  253,  165,
      168,  168,  168,  174,  166,  172,  172,  172,  306,  258,
      254,  255,  256,  255,  256,  259,  260,  257,  257,  257,

      178,  172,  172,  172,  307,  254,  255,  258,  490,  174,
      261,  255,   90,  259,   90,  281,  295,  489,  282,  252,
      252,  252,  260,  296,  488,  330,  178,   90,  261,  252,
      252,  252,   90,  257,  257,  257,  257,  257,  257,  326,
      163,  326,  163,  330,  327,  327,  327,  170,  372,  170,
      328,  329,  363,  373,  384,  163,  487,  374,  329,  486,
      163,  485,  170,  327,  327,  327,  364,  170,  328,  327,
      327,  327,  384,  480,  484,  483,  482,  329,  479,  481,
      255,  478,  255,  477,  329,  476,  475,  474,  473,  472,
      471,  470,  469,  468,  467,  255,  466,  465,  464,  463,

      255,   61,   61,   61,   61,   65,  462,   65,   65,   70,
       70,   70,   70,  103,  103,  164,  164,  164,  164,  167,
      461,  167,  167,  249,  460,  249,  249,  166,  166,  166,
      166,  459,  458,  457,  456,  455,  454,  453,  452,  451,
      450,  449,  448,  447,  446,  445,  444,  443,  442,  441,
      440,  439,  438,  437,  436,  435,  434,  433,  432,  431,
      430,  429,  428,  427,  426,  425,  424,  423,  422,  421,
      420,  419,  418,  417,  416,  415,  414,  413,  412,  411,
      410,  409,  408,  407,  406,  405,  404,  403,  402,  401,
      400,  399,  398,  397,  396,  395,  394,  393,  392,  391,

      390,  389,  388,  387,  386,  385,  383,  382,  381,  380,
      379,  378,  377,  376,  375,  371,  370,  369,  368,  367,
      366,  365,  362,  361,  360,  359,  358,  357,  356,  355,
      354,  353,  352,  351,  350,  349,  348,  347,  346,  345,
      344,  343,  342,  341,  340,  339,  338,  337,  336,  335,
      334,  333,  332,  331,  159,  250,  325,  324,  323,  322,
      321,  320,  319,  318,  317,  316,  315,  314,  313,  312,
      311,  310,  305,  304,  303,  302,  301,  300,  299,  298,
      297,  294,  293,  292,  291,  290,  289,  288,  287,  286,
      285,  284,  283,  280,  279,  278,  277,  276,  275,  274,

      273,  272,  269,  268,  267,  266,  265,  264,  263,  262,
      250,  248,  247,  244,  243,  242,  238,  233,  232,  226,
      225,  221,  220,  217,  216,  215,  214,  213,  212,  211,
      210,  207,  206,  205,  204,  203,  198,  197,  196,  190,
      189,  188,  187,  184,  183,  182,  181,  180,  161,  160,
      159,   66,   59,  140,  139,  135,  126,  107,  106,  100,
       97,   74,   67,   66,   60,   59,  495,    3,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,

      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495
    } ;

static yyconst flex_int16_t yy_chk[737] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    9,   12,
       13,    9,   17,   26,   26,   28,   28,   13,   19,   21,
      110,  110,   42,   17,   21,   12,   20,   19,   19,   42,
       20,   21,   20,   20,   20,   31,  502,   36,   56,   31,

       36,    9,   37,   13,   22,   37,   22,   22,   22,   37,
       37,   44,   37,   43,   38,   37,   22,   22,   43,   22,
       22,   22,   39,   38,   39,   40,   47,  120,  493,   87,
       44,   22,   22,   38,   39,   40,   45,   22,   40,   56,
       45,   40,   47,  120,   50,   47,   22,   50,   50,   22,
       23,  492,   23,   23,   23,   52,   51,   87,   50,   51,
       52,   50,   23,   23,   54,   23,   23,   53,   51,   54,
       61,   53,   70,   61,  105,   51,   53,   23,   23,   70,
      231,  105,   83,   23,   82,   82,   82,   83,   86,   86,
       86,  231,   23,   92,   82,   82,  121,   82,   86,   86,

      121,   86,  148,   61,  128,   70,  148,  105,  147,   82,
       82,   92,  128,   86,   86,   82,  147,   96,   88,   86,
       88,   88,   88,   91,   91,   95,   95,  191,  191,  115,
       88,   88,   89,   88,   89,   96,  115,   89,   89,   89,
      488,   91,  143,   95,  104,   88,   88,  104,  116,  137,
       91,   88,   95,  116,  137,  140,  144,  140,  116,  144,
      143,  150,  154,  164,  154,  487,  150,  140,  164,  162,
      150,  162,  144,  165,  162,  162,  162,  104,  165,  166,
      168,  168,  168,  173,  166,  171,  171,  171,  229,  175,
      168,  168,  169,  168,  169,  176,  176,  169,  169,  169,

      177,  172,  172,  172,  229,  168,  168,  175,  486,  173,
      179,  168,  172,  176,  172,  201,  218,  485,  201,  251,
      251,  251,  176,  218,  484,  260,  177,  172,  179,  252,
      252,  252,  172,  256,  256,  256,  257,  257,  257,  254,
      252,  254,  252,  260,  254,  254,  254,  257,  315,  257,
      259,  259,  305,  315,  330,  252,  483,  315,  328,  481,
      252,  480,  257,  326,  326,  326,  305,  257,  259,  327,
      327,  327,  330,  475,  478,  477,  476,  259,  474,  475,
      327,  473,  327,  472,  328,  471,  469,  468,  467,  465,
      463,  462,  459,  456,  455,  327,  453,  452,  450,  448,

      327,  496,  496,  496,  496,  497,  446,  497,  497,  498,
      498,  498,  498,  499,  499,  500,  500,  500,  500,  501,
      444,  501,  501,  503,  442,  503,  503,  504,  504,  504,
      504,  441,  440,  438,  437,  436,  435,  434,  432,  431,
      430,  428,  427,  425,  424,  423,  422,  421,  419,  418,
      417,  415,  414,  410,  405,  404,  402,  401,  400,  398,
      397,  396,  391,  390,  387,  386,  385,  382,  381,  380,
      379,  377,  376,  374,  373,  372,  370,  369,  368,  367,
      366,  364,  363,  362,  360,  359,  358,  356,  355,  354,
      353,  352,  351,  350,  349,  348,  347,  344,  343,  342,

      341,  340,  338,  337,  336,  335,  325,  324,  323,  321,
      320,  319,  318,  317,  316,  313,  311,  310,  309,  308,
      307,  306,  304,  303,  302,  301,  300,  299,  298,  297,
      296,  295,  294,  293,  292,  291,  288,  286,  285,  284,
      283,  282,  281,  277,  276,  275,  274,  273,  271,  270,
      269,  267,  266,  264,  250,  249,  248,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  238,  236,  235,  234,
      233,  232,  228,  227,  226,  224,  223,  222,  221,  220,
      219,  217,  216,  214,  213,  211,  210,  208,  207,  206,
      204,  203,  202,  200,  199,  198,  197,  196,  195,  194,

      193,  192,  190,  188,  187,  186,  185,  184,  183,  182,
      159,  156,  155,  153,  152,  151,  149,  146,  145,  142,
      141,  139,  138,  136,  135,  134,  133,  132,  131,  130,
      129,  126,  125,  124,  123,  122,  119,  118,  117,  114,
      113,  112,  111,  109,  108,  107,  102,   98,   81,   79,
       66,   65,   59,   49,   48,   46,   41,   35,   34,   27,
       24,   16,   11,   10,    8,    5,    3,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,

      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "scanner.lex"
#line 2 "scanner.lex"
#include "scanner.h"
/* ------------------- definitions -------------------- */
/* newline */
/* anything but newline */
/* any of 256 source characters */
/* backslash */
/* beginnging of line (must be start of a pattern) */
/* end of line (would like EOF to qualify also, but flex doesn't allow it */
/* letter or underscore */
/* letter or underscore or digit */
/* decimal digit */
/* sequence of decimal digits */
/* sequence of hex digits */
/* sign of a number */
/* integer suffix */
/* added 'LL' option for gcc/c99 long long compatibility */
/* floating-point suffix letter */
/* normal string character: any but quote, newline, or backslash */
/* (start of) an escape sequence */
/* double quote */
/* normal character literal character: any but single-quote, newline, or backslash */
/* single quote */
/* space or tab */
/* preprocessor "character" -- any but escaped newline */
#line 768 "lex.yy.cc"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 74 "scanner.lex"



  /* operators, punctuators and keywords: tokens with one spelling */
#line 878 "lex.yy.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = & std::cin;

		if ( ! yyout )
			yyout = & std::cout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 496 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 668 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 78 "scanner.lex"
*yyout << "[TYPE]";
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 79 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 80 "scanner.lex"
*yyout << "[TYPE]";
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 81 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 82 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 83 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 84 "scanner.lex"
*yyout << "[TYPE]";
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 85 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 86 "scanner.lex"
*yyout << "[KWORD]";
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 87 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 88 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 89 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 90 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 91 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 92 "scanner.lex"
*yyout << "[TYPE]";
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 93 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 94 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 95 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 96 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 97 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 98 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 99 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 100 "scanner.lex"
*yyout << "[TYPE]";
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 101 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 102 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 103 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 104 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 105 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 106 "scanner.lex"
*yyout << "[TYPE]";
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 107 "scanner.lex"
*yyout << "[TYPE]";
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 108 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 109 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 110 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 111 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 112 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 113 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 114 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 115 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 116 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 117 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 118 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 119 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 120 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 121 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 122 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 123 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 124 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 125 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 126 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 127 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 128 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 129 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 130 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 131 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 132 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 133 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 134 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 135 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 136 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 137 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 138 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 139 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 140 "scanner.lex"
*yyout << "[TYPE]";
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 141 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 143 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 144 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 145 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 146 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 147 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 148 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 149 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 150 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 151 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 152 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 153 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 154 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 155 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 156 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 157 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 158 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 162 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 163 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 164 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 165 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 166 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 167 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 168 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 169 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 170 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 171 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 172 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 173 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 174 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 175 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 176 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 177 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 178 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 179 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 180 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 181 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 182 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 183 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 184 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 185 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 186 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 187 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 188 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 189 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 190 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 191 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 192 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 193 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 194 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 195 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 196 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 197 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 198 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 199 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 200 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 201 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 202 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 203 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 204 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 205 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 206 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 207 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 208 "scanner.lex"
*yyout << YYText();
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 209 "scanner.lex"

	YY_BREAK
case 129:
YY_RULE_SETUP
#line 210 "scanner.lex"

	YY_BREAK
/* end of line */
case 130:
/* rule 130 can match eol */
YY_RULE_SETUP
#line 213 "scanner.lex"
{
  *yyout << YYText();
}
	YY_BREAK
/* integer literal; dec, oct, or hex */
case 131:
#line 219 "scanner.lex"
case 132:
#line 220 "scanner.lex"
case 133:
YY_RULE_SETUP
#line 220 "scanner.lex"
{
  *yyout << "[INT]";
}
	YY_BREAK
/* hex literal with nothing after the 'x' */
case 134:
YY_RULE_SETUP
#line 225 "scanner.lex"
{
  *yyout << "[INT]";
}
	YY_BREAK
/* identifier: e.g. foo */
case 135:
YY_RULE_SETUP
#line 230 "scanner.lex"
{
  *yyout << "[ID]";
}
	YY_BREAK
/* floating literal */
case 136:
#line 236 "scanner.lex"
case 137:
#line 237 "scanner.lex"
case 138:
YY_RULE_SETUP
#line 237 "scanner.lex"
{
  *yyout << "[FLT]";
}
	YY_BREAK
/* floating literal with no digits after the 'e' */
case 139:
#line 243 "scanner.lex"
case 140:
#line 244 "scanner.lex"
case 141:
YY_RULE_SETUP
#line 244 "scanner.lex"
{

  /* in recovery rules like this it's best to yield the best-guess
   * token type, instead of some TOK_ERROR, so the parser can still
   * try to make sense of the input; having reported the error is
   * sufficient to ensure that later stages won't try to interpret
   * the lexical text of this token as a floating literal */
  *yyout << "[FLT]";
}
	YY_BREAK
/* string literal */
case 142:
/* rule 142 can match eol */
YY_RULE_SETUP
#line 255 "scanner.lex"
{
  *yyout << "[STR]";
}
	YY_BREAK
/* string literal missing final quote */
case 143:
/* rule 143 can match eol */
YY_RULE_SETUP
#line 260 "scanner.lex"
{
    *yyout << "[STR]";
}
	YY_BREAK
/* character literal */
case 144:
/* rule 144 can match eol */
YY_RULE_SETUP
#line 265 "scanner.lex"
{
  *yyout << "[CHAR]";
}
	YY_BREAK
/* character literal missing final tick */
case 145:
/* rule 145 can match eol */
YY_RULE_SETUP
#line 270 "scanner.lex"
{
  *yyout << "[CHAR]";
}
	YY_BREAK
/* unterminated character literal */
case 146:
/* rule 146 can match eol */
YY_RULE_SETUP
#line 275 "scanner.lex"
{
  *yyout << "[CHAR]";
}
	YY_BREAK
/* preprocessor */
/* technically, if this isn't at the start of a line (possibly after
   * some whitespace), it should be an error.. I'm not sure right now how
   * I want to deal with that (I originally was using '^', but that
   * interacts badly with the whitespace rule) */
/* other preprocessing: ignore it */
/* trailing optional baskslash to avoid backing up */
case 147:
/* rule 147 can match eol */
YY_RULE_SETUP
#line 288 "scanner.lex"
{
  // ignore ?
}
	YY_BREAK
/* whitespace */
/* 10/20/02: added '\r' to accomodate files coming from Windows; this
   * could be seen as part of the mapping from physical source file
   * characters to the basic character set (cppstd 2.1 para 1 phase 1),
   * except that it doesn't happen for chars in string/char literals... */
case 148:
YY_RULE_SETUP
#line 297 "scanner.lex"
{
    // delete whitespace
}
	YY_BREAK
/* C++ comment */
/* we don't match the \n because that way this works at EOF */
case 149:
YY_RULE_SETUP
#line 303 "scanner.lex"
{
  // delete comment
}
	YY_BREAK
/* C comment */
case 150:
/* rule 150 can match eol */
YY_RULE_SETUP
#line 308 "scanner.lex"
{
  // delete comment
}
	YY_BREAK
/* unterminated C comment */
case 151:
/* rule 151 can match eol */
YY_RULE_SETUP
#line 313 "scanner.lex"
{
  // delete comment
}
	YY_BREAK
/* else */
case 152:
YY_RULE_SETUP
#line 321 "scanner.lex"
{
  *yyout << YYText();
}
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 325 "scanner.lex"
ECHO;
	YY_BREAK
#line 1785 "lex.yy.cc"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout )
{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = 0;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree(yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree(yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if ( new_in )
		{
		yy_delete_buffer( YY_CURRENT_BUFFER );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );
		}

	if ( new_out )
		yyout = new_out;
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout->write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 496 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 496 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 495);

	return yy_is_jam ? 0 : yy_current_state;
}

    void yyFlexLexer::yyunput( int c, register char* yy_bp)
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream* input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

extern "C" int isatty (int );

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream* file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc(new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( yyconst char msg[] )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 325 "scanner.lex"



int yyFlexLexer::yywrap(void)
{
    return 1;
}

